seed: 3407

d_model: 128
d_alphabet: 27 # 26 + 1 for `'`
d_phoneme: 71
d_special: 3
pad_idx: 0
sos_idx: 1
eos_idx: 2

batch_size: 512
tf_ratio: 0.5
epochs: 30
lr: 0.0025
lr_decay: 0.9

dropout: 0.3

alphabets:
  [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "'",
  ]
phonemes:
  [
    "aa0",
    "aa1",
    "aa2",
    "ae0",
    "ae1",
    "ae2",
    "ah0",
    "ah1",
    "ah2",
    "ao0",
    "ao1",
    "ao2",
    "aw0",
    "aw1",
    "aw2",
    "ax",
    "axr",
    "ay0",
    "ay1",
    "ay2",
    "b",
    "ch",
    "d",
    "dh",
    "eh0",
    "eh1",
    "eh2",
    "er0",
    "er1",
    "er2",
    "ey0",
    "ey1",
    "ey2",
    "f",
    "g",
    "hh",
    "ih0",
    "ih1",
    "ih2",
    "iy0",
    "iy1",
    "iy2",
    "jh",
    "k",
    "l",
    "m",
    "n",
    "ng",
    "ow0",
    "ow1",
    "ow2",
    "oy0",
    "oy1",
    "oy2",
    "p",
    "r",
    "s",
    "sh",
    "t",
    "th",
    "uh0",
    "uh1",
    "uh2",
    "uw0",
    "uw1",
    "uw2",
    "v",
    "w",
    "y",
    "z",
    "zh",
  ]
specials: ["<pad>", "<sos>", "<eos>"]
